CREATE TABLE Students(
	Reg_ID varchar(15) NOT NULL,
	DOB date NULL,
	Student_Name varchar(35) NOT NULL,
	Father_Name varchar(35) NULL,
	FatherOccupation varchar(30) NULL,
	FatherIncome number(6) NULL,
	Gender number(3) NOT NULL,
	CNIC varchar(20) NULL,
	BloodGroup varchar(5) NULL,
	Photo blob NULL,
	Email varchar(30) NULL,
	Area number(3) NULL,
	Current_Program_ID varchar(4) NOT NULL,
	Phone_Home varchar(20) NULL,
	Phone_Office1 varchar(20) NULL,
	Phone_Office2 varchar(20) NULL,
	Phone_Mobile1 varchar(20) NULL,
	Phone_Mobile2 varchar(20) NULL,
	PostalAddressL1 varchar(100) NULL,
	PostalAddressL2 varchar(100) NULL,
	PACity_ID smallint NULL,
	PermanentAddressL1 varchar(100) NULL,
	PermanentAddressL2 varchar(100) NULL,
	PerACity_ID smallint NULL,
	EmergencyContactName varchar(50) NULL,
	EmergencyContactPhone1 varchar(20) NULL,
	EmergencyContactPhone2 varchar(20) NULL,
	EmergencyContactRelationship varchar(20) NULL,
	District_ID smallint NULL,
	IDCard varchar(20) NULL,
	Modified_On date NULL,
	IsPosed number(3) NOT NULL);